---
title: "limpieza surveys"
format: html
editor: visual
---

## LIMPIEZA DE DATOS

```{r}
rm(list = ls())
library(tidyverse)
```

```{r}
election_data <- read_csv(file = "../data/data/datos_elecciones_brutos.csv")
cod_mun <- read_csv(file = "../data/data/cod_mun.csv")
surveys <- read_csv(file = "../data/data/historical_surveys.csv")
abbrev <- read_csv(file = "../data/data/siglas.csv")
```

LIMPIEZA DE LOS DATOS

SURVEYS

"PARTIDO SOCIALISTA OBRERO ESPAÑOL"

"PARTIDO POPULAR"

"CIUDADANOS"

"PARTIDO NACIONALISTA VASCO"

"BLOQUE NACIONALISTA GALLEGO"

"CONVERGÈNCIA I UNIÓ"

"UNIDAS PODEMOS - IU"

"ESQUERRA REPUBLICANA DE CATALUNYA"

"EH - BILDU"

"MÁS PAÍS"

"VOX"

```{r}
partidos_a_filtrar <- c("PARTIDO SOCIALISTA OBRERO ESPAÑOL", "PSOE", 
                        "PARTIDO POPULAR", 
                        "CIUDADANOS", "C'S", 
                        "PARTIDO NACIONALISTA VASCO", "EAJ-PNV", 
                        "BLOQUE NACIONALISTA GALLEGO", "BNG", 
                        "CONVERGÈNCIA I UNIÓ", "CDC", 
                        "UNIDAS PODEMOS", "IU", "PODEM", "EZKER BATUA", 
                        "ESQUERRA REPUBLICANA DE CATALUNYA", "ERC", 
                        "EH - BILDU", "SORTU", "EUSKO ALKARTASUNA", 
                        "ALTERNATIBA", "ARALAR", 
                        "MÁS PAÍS", "VOX")

filtrado <- abbrev |> 
    filter(str_detect(denominacion, str_c(partidos_a_filtrar, collapse = "|"))) |>
  filter(!denominacion %in% c("PARTIDO DE ASOCIACION DE VIUDAS Y ESPOSAS LEGALES", "CONVERGENCIA CIUDADANA DEL SURESTE", "PARTIU ASTURIANISTA", "CIUDADANOS EN BLANCO", "AGRUPACION CIUDADANA", "INICIATIVA CIUDADANA BURGALESA", "PARTIDO CIUDADANOS UNIDOS DE ARAGON", "UNION CIUDADANA PROGRESISTAS INDEPENDIENTES DE CANARIAS", "CIUDADANOS DE CENTRO DEMOCRÁTICO", "FORO DE CIUDADANOS", "ACCION CIUDADANA POR MALAGA", "UNION DE CIUDADANOS INDEPENDIENTES DE TOLEDO", "CIUDADANOS DE CENTRO DEMOCRATICO-CANDIDATURA INDEP", "EN POSITIU", "JUSTIZIA SOCIAL, PARTICIPACION CIUDADANA", "POBLE LLIURE - SOM ALTERNATIVA - PIRATES DE CATALU", "CIUDADANOS INDEPENDIENTES DE LINARES UNIDOS", "MOVIMIENTO POR LA DIGNIDAD Y LA CIUDADANÍA DE CEUT","CIUDADANOS LIBRES UNIDOS", "CIUDADANOS RURALES AGRUPADOS", "CIUDADANOS DE CENTRO DEMOCRÁTICO-CANDIDATURA INDEP", "JUSTIZIA SOCIAL, PARTICIPACIÓN CIUDADANA"
))|> 
  group_by(denominacion) |> 
  summarise(siglas = first(siglas), .groups = "drop") # Unificar duplicados
filtrado
```

```{r}
tidy_surveys<-
  surveys |> 
  pivot_longer(cols = -c(type_survey : turnout), names_to= "partidos",
               values_to = "count", values_drop_na = TRUE)
tidy_surveys
```

```{r}
tidy_surveys<- tidy_surveys |> 
  filter(date_elec>= "2008-01-01") |> 
  select(-type_survey)
```

```{r}
tidy_surveys<- tidy_surveys |> 
  left_join(filtrado, by = c("partidos" = "siglas")) |> 
  mutate(partido = if_else(partidos %in% filtrado$siglas, partidos, "OTROS")) |> 
  select(-partidos) |> 
  relocate(partido, .before = turnout)
```

```{r}
tidy_surveys <- tidy_surveys |> 
  group_by(
    date_elec,       # Fecha de la elección
    id_pollster,     # Identificador de la casa encuestadora
    pollster,        # Nombre de la casa encuestadora
    media,           # Medio asociado
    partido         # Partido (incluyendo "OTROS")
  ) |> 
  summarise(
    count = sum(count, na.rm = TRUE),   # Sumar votos por partido
    field_date_from = first(field_date_from),  # Duración del trabajo de campo (igual para todas las filas de una encuesta)
    field_date_to = first(field_date_to),
    exit_poll = first(exit_poll),      # Si es o no encuesta a pie de urna (debe ser igual dentro del grupo)
    size = first(size),                # Tamaño muestral
    turnout = first(turnout),          # Participación estimada
    .groups = "drop"                   # Eliminar niveles de agrupación
  )
```

```{r}
tidy_surveys<- tidy_surveys |> 
  filter(exit_poll!= TRUE) |> 
  filter(!is.na(size) & size >= 500)
tidy_surveys
```

```{r}
tidy_surveys<- tidy_surveys |> 
  mutate(field_duration = ymd(field_date_to) - ymd(field_date_from)) |> 
  filter(field_duration > 1) |> 
  select(-c(field_date_from, field_date_to)) |> 
  relocate(field_duration, .after = media)
tidy_surveys
```
