---
title: "pregunta_8"
format: html
editor: visual
---

## PREGUNTA 8 - ADICIONAL

¿Cómo evolucionaron las preferencias hacia los partidos nacionalistas/regionalistas en comparación con los partidos nacionales durante el período 2008-2019?

```{r}
partidos_clasificados <- datos_elecciones_tidy |> 
  mutate(
    grupo_partido = case_when(
      partido %in% c("EAJ-PNV", "BNG", "CIU", "ERC", "EH-BILDU") ~ "NACIONALISTA/REGIONALISTA",
      partido %in% c("PSOE", "PP", "C's", "VOX", "PODEMOS", "MÁS PAÍS", "PODEMOS-COM", "PODEMOS-EUP", "PODEMOS-IU-EQUO") ~ "NACIONAL",
      TRUE ~ NA_character_)
  ) |> 
  filter(!is.na(grupo_partido) & anno >= 2008 & anno <= 2019)

# Agrupamos por año y grupo de partido. Además, sumamos los votos
datos_agrupados8 <- partidos_clasificados |> 
  group_by(anno, grupo_partido) |> 
  summarise(total_votos = sum(votos, na.rm = TRUE), .groups = "drop")

# Calculamos el porcentaje de votos por grupo dentro de cada año
porcentajes8 <- datos_agrupados8 |> 
  group_by(anno) |> 
  mutate(porcentaje_votos = (total_votos / sum(total_votos)) * 100) |> 
  ungroup()
partidos_clasificados
```

```{r}
grafico8 <- porcentajes8 |> 
  ggplot(aes(x = anno, y = porcentaje_votos, color = grupo_partido, group = grupo_partido)) +
  geom_line(size = 0.75) +
  geom_point(size = 2) +
  geom_text(aes(label = paste0(round(porcentaje_votos, 1), "%")),
            position = position_nudge(y = 5), size = 3) +  # Añade las etiquetas con el porcentaje y su posicion y tamaño
  labs(
    title = "Evolución de las preferencias por tipo de partido (2008-2019)",
    x = "Año",
    y = "Porcentaje de votos",
    color = "Tipo de partido"
  ) +
  theme_minimal() +
  scale_color_manual(values = c(
    "NACIONALISTA/REGIONALISTA" = "#FF5733",  # Naranja
    "NACIONAL" = "#1F77B4"                   # Azul
  )) +
  scale_x_continuous(breaks = seq(2008, 2019, 1))  # Asegura que los años sean enteros y aparezcan de uno en uno
grafico8
```
